import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* create a navigation bar using links, to home and notes */}
        <nav className="flex justify-between items-center p-4 border-b border-gray-200">
          <div className="flex items-center space-x-4">
            <Link href="/" className="text-lg font-semibold">
              Home
            </Link>
            <Link href="/notes" className="text-lg font-semibold">
              Notes
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
